language: python
python: 3.3
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=coverage
    - TOXENV=flake8
    - TOXENV=pylint

install:
  - pip install tox -f wheelhouse
  - if test "$TOXENV" = coverage ; then pip install python-coveralls ; fi
script: tox
after_success:
  - if test "$TOXENV" = coverage ; then coveralls ; fi
