sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install tox-travis
script:
  - tox
jobs:
  include:
    - python: 3.6
      env: TOXENV=coverage
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=mypy
after_success:
  - if test "$TOXENV" = coverage ; then pip install coveralls; coveralls ; fi
  - if test "$TOXENV" = coverage ; then pip install codecov; codecov ; fi
