language: python
python: 3.3
env:
  matrix:
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=coverage
    - TOXENV=flake8

before_install:
  - if test "$TOXENV" = py34 ; then sudo apt-get update ; fi
  - if test "$TOXENV" = py34 ; then sudo apt-get install python3.4 python3.4-dev ; fi

install:
  - pip install tox
  - if test "$TOXENV" = coverage ; then pip install python-coveralls ; fi
script: tox
after_success:
  - if test "$TOXENV" = coverage ; then coveralls ; fi
