language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e .[testing] -c constraints.txt
script:
  - flake8 webdispatch
  - pylint webdispatch
  - py.test webdispatch --cov=webdispatch --cov-report=term-missing
after_success:
  - if test "$TOXENV" = coverage ; then coveralls ; fi
