language: python
python: 3.3
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=coverage

before_install:
  - sudo apt-get update
  - sudo apt-get install python3.4 python3.4-dev

install: pip install tox python-coveralls
script: tox
after_success:
  - coveralls